{% set name = "pydantic-numpy" %}
{% set version = "9.0.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_numpy-{{ version }}.tar.gz
  sha256: e079c87f5c1412f1c9c1e04902c608a91e6365bbc0932bd6ea3ab7bdd5350b8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python {{ python_min }}
    - compress-pickle
    - ruamel.yaml >=0.18.5,<0.19.0
    - numpy >=2.0.0
    - pydantic >=2.0.0,<3.0.0
    - semver >=3.0.1,<4.0.0

test:
  imports:
    - pydantic_numpy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/caniko/pydantic-numpy
  summary: Pydantic Model integration of the NumPy array
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/caniko/pydantic-numpy

extra:
  recipe-maintainers:
    - caniko
    - apcamargo
